[package]
name = "odyssey-cookbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = {version = "0.2.4", features = ["desktop"] }
dioxus-core = "0.2.1"
dioxus-desktop = "0.2.3"
dioxus-heroicons = {path = "/Users/james/Documents/Projects/dioxus-heroicons/"}
